services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  Tourze\LarkOAuth2LoginBundle\Repository\:
    resource: "../../Repository/"
  Tourze\LarkOAuth2LoginBundle\Service\:
    resource: "../../Service/"
  Tourze\LarkOAuth2LoginBundle\Controller\:
    resource: "../../Controller/"
    tags: ['controller.service_arguments']
  Tourze\LarkOAuth2LoginBundle\Factory\:
    resource: "../../Factory/"
